apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prd
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: in-cluster
      namespace: production
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

