apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stg-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: in-cluster
      namespace: staging
  sourceRepos:
    - '*'
