apiVersion: v1
kind: Service
metadata:
  name: hostaway
spec:
  selector:
    app: hostaway
  ports:
    - port: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hostaway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hostaway
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostaway
spec:
  selector:
    matchLabels:
      app: hostaway
  template:
    metadata:
      labels:
        app: hostaway
    spec:
      containers:
        - name: hostaway
          # Changed in the overlays
          image: hostaway:latest
          resources:
            requests:
              cpu: 250m
              memory: "64Mi"
            limits:
              memory: "64Mi"
          ports:
            - containerPort: 80
