server:
  service:
    type: LoadBalancer
    servicePortHttp: 20080
    servicePortHttps: 20443
  extraArgs:
    # Avoids security warnings (locally it's fine)
    - --insecure
# Regarding listening to a local repository
# See https://github.com/argoproj/argo-cd/discussions/9912#discussioncomment-13722256
repoServer:
  volumes:
    - name: local-repo
      hostPath:
        path: /mnt/source
        type: Directory
    - name: git-config
      configMap:
        name: git-config
  volumeMounts:
    - name: local-repo
      mountPath: /mnt/source
    - name: git-config
      mountPath: /etc/gitconfig
      subPath: gitconfig
config:
  repositories:
    source:
      type: git
      name: source
      url: file:///mnt/source
# Avoiding the ownership error introduced in argocd v2.12
# See https://github.com/argoproj/argo-cd/issues/19727#issuecomment-2809571263
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: git-config
    data:
      gitconfig: |
        [filter "lfs"]
          clean = git-lfs clean -- %f
          smudge = git-lfs smudge -- %f
          process = git-lfs filter-process
          required = true

        [safe]
          directory = *
