apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: file:///mnt/source
        revision: main
        directories:
          - path: gitops/tenants/*/overlays/stg
          - path: gitops/tenants/*/overlays/prd
  template:
    metadata:
      name: "{{index .path.segments 2}}-{{.path.basename}}"
    spec:
      project: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: file:///mnt/source
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{if eq .path.basename \"stg\"}}staging{{else}}production{{end}}"
