name: Production

on:
  push:
    branches:
      - main
    paths:
      - version.txt
      - CHANGELOG.md
      - .release-please-manifest.json

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yaml
    permissions:
      contents: write
      pull-requests: write
      issues: write
    with:
      environment: prd

  retag-img:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - release-please
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag the docker image
        shell: bash
        env:
          FROM_TAG: latest
          TO_TAG: ${{ needs.release-please.outputs.tag_name }}
          IMAGE_FQN: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          if [ -z "${TO_TAG}" ]; then
            echo "No tag specified, exiting"
            exit 1
          fi
          docker pull "${IMAGE_FQN}:${FROM_TAG}"
          docker tag "${IMAGE_FQN}:${FROM_TAG}" "${IMAGE_FQN}:${TO_TAG}"
          docker push "${IMAGE_FQN}:${TO_TAG}"

  deploy:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: write
    needs:
      - retag-img
      - release-please
    with:
      environment: prd
      version: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
