name: Production

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  retag-img:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag the docker image
        shell: bash
        env:
          FROM_TAG: latest
          TO_TAG: ${{ github.ref_name}}
          IMAGE_FQN: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          docker pull "${IMAGE_FQN}:${FROM_TAG}"
          docker tag "${IMAGE_FQN}:${FROM_TAG}" "${IMAGE_FQN}:${TO_TAG}"
          docker push "${IMAGE_FQN}:${TO_TAG}"
