name: Production

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  retag-img:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolves Git SHA
        id: resolved-sha
        shell: bash
        env:
          RESOLVED_SHA: ${{ github.sha }}
        run: |
          echo "value=${RESOLVED_SHA::8}" >> "${GITHUB_OUTPUT}"

      - name: Retag the docker image
        shell: bash
        env:
          FROM_TAG: ${{ steps.resolved-sha.outputs.value }}
          TO_TAG: ${{ github.ref_name}}
        run: |
          docker pull "${IMAGE_NAME}:${FROM_TAG}"
          docker tag "${IMAGE_NAME}:${FROM_TAG}" "${IMAGE_NAME}:${TO_TAG}"
          docker push "${IMAGE_NAME}:${TO_TAG}"
